<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="LinqKit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\2 - Domain\IHunger.Domain\IHunger.Domain.csproj" />
  </ItemGroup>

</Project>
